apiVersion: v1
kind: Pod
metadata:
    name: django-todo-pod
    namespace: django-todo-app
spec:
  containers:
    - name: django-todo-ctr
      image: rishhe/react-django:latest
      ports:
        - containerPort: 8001
