apiVersion: v1
kind: Service
metadata:
  name: django-todo-service
  namespce: django-todo-app
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 9376
  
